-- This script was generated by Lokasenna_Show only specified tracks.lua
package.path = reaper.GetResourcePath() .. '/Scripts/ReaSonus/?.lua'
local showTracks = require("showTracksByName")

local settings = {
  showsiblings = false,
  showparents = true,
  matchonlytop = false,
  search = "Drum|drm",
  showchildren = true,
  matchmultiple = false,
}

showTracks.showTracks(settings)

return
