on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Make
        if: startsWith(github.ref, 'refs/tags/')
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REAPER_PATH: dummy
          ALWAYS_ON_ACTION: dummy
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ReaSonus FaderPort
          path: out/*.zip
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          draft: false
          prerelease: true
          files: |
            out/*.zip
